# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.2.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHeaderView, QLabel, QLineEdit, QProgressBar,
    QPushButton, QSizePolicy, QSpinBox, QTabWidget,
    QTableWidget, QTableWidgetItem, QWidget)
import resources_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.setEnabled(True)
        Form.resize(779, 638)
        Form.setMinimumSize(QSize(661, 601))
        icon = QIcon()
        icon.addFile(u":/IR-System/resource/IRSystem-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        Form.setWindowIcon(icon)
        self.func_comboBox = QComboBox(Form)
        self.func_comboBox.addItem("")
        self.func_comboBox.addItem("")
        self.func_comboBox.addItem("")
        self.func_comboBox.addItem("")
        self.func_comboBox.addItem("")
        self.func_comboBox.addItem("")
        self.func_comboBox.setObjectName(u"func_comboBox")
        self.func_comboBox.setGeometry(QRect(10, 40, 341, 21))
        self.func_comboBox.setDuplicatesEnabled(False)
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 16, 291, 20))
        self.file_label = QLabel(Form)
        self.file_label.setObjectName(u"file_label")
        self.file_label.setGeometry(QRect(10, 70, 151, 16))
        self.file_progressBar = QProgressBar(Form)
        self.file_progressBar.setObjectName(u"file_progressBar")
        self.file_progressBar.setGeometry(QRect(10, 90, 381, 23))
        self.file_progressBar.setValue(24)
        self.file_spinBox = QSpinBox(Form)
        self.file_spinBox.setObjectName(u"file_spinBox")
        self.file_spinBox.setGeometry(QRect(560, 40, 71, 22))
        self.file_spinBox.setReadOnly(False)
        self.file_spinBox.setAccelerated(True)
        self.file_spinBox.setMinimum(1)
        self.file_spinBox.setMaximum(1000)
        self.file_spinBox.setValue(25)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(460, 40, 90, 16))
        self.Stemming_checkBox = QCheckBox(Form)
        self.Stemming_checkBox.setObjectName(u"Stemming_checkBox")
        self.Stemming_checkBox.setGeometry(QRect(510, 90, 141, 20))
        self.Stemming_checkBox.setAutoFillBackground(False)
        icon1 = QIcon()
        icon1.addFile(u":/IR-System/resource/Stemming-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Stemming_checkBox.setIcon(icon1)
        self.Stemming_checkBox.setChecked(True)
        self.Stopwords_checkBox = QCheckBox(Form)
        self.Stopwords_checkBox.setObjectName(u"Stopwords_checkBox")
        self.Stopwords_checkBox.setGeometry(QRect(400, 90, 101, 20))
        icon2 = QIcon()
        icon2.addFile(u":/IR-System/resource/stopwords-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Stopwords_checkBox.setIcon(icon2)
        self.Stopwords_checkBox.setChecked(True)
        self.file_label_2 = QLabel(Form)
        self.file_label_2.setObjectName(u"file_label_2")
        self.file_label_2.setGeometry(QRect(50, 120, 151, 16))
        self.perform_pushButton = QPushButton(Form)
        self.perform_pushButton.setObjectName(u"perform_pushButton")
        self.perform_pushButton.setGeometry(QRect(360, 40, 81, 21))
        icon3 = QIcon()
        icon3.addFile(u":/IR-System/resource/Play-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.perform_pushButton.setIcon(icon3)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 120, 53, 16))
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 140, 761, 491))
        self.tabWidget.setAutoFillBackground(False)
        self.Zipf_tab = QWidget()
        self.Zipf_tab.setObjectName(u"Zipf_tab")
        self.Index_tableWidget = QTableWidget(self.Zipf_tab)
        if (self.Index_tableWidget.columnCount() < 3):
            self.Index_tableWidget.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.Index_tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.Index_tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.Index_tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.Index_tableWidget.setObjectName(u"Index_tableWidget")
        self.Index_tableWidget.setGeometry(QRect(10, 10, 741, 291))
        self.Index_tableWidget.setFrameShadow(QFrame.Raised)
        self.IgnoreCase_checkBox = QCheckBox(self.Zipf_tab)
        self.IgnoreCase_checkBox.setObjectName(u"IgnoreCase_checkBox")
        self.IgnoreCase_checkBox.setGeometry(QRect(520, 310, 111, 20))
        self.IgnoreCase_checkBox.setAutoFillBackground(False)
        icon4 = QIcon()
        icon4.addFile(u":/IR-System/resource/IgnoreCase-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.IgnoreCase_checkBox.setIcon(icon4)
        self.IgnoreCase_checkBox.setChecked(False)
        self.file_label_3 = QLabel(self.Zipf_tab)
        self.file_label_3.setObjectName(u"file_label_3")
        self.file_label_3.setGeometry(QRect(10, 310, 61, 16))
        self.search_pushButton = QPushButton(self.Zipf_tab)
        self.search_pushButton.setObjectName(u"search_pushButton")
        self.search_pushButton.setGeometry(QRect(250, 310, 71, 20))
        icon5 = QIcon()
        icon5.addFile(u":/IR-System/resource/Search-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.search_pushButton.setIcon(icon5)
        self.Partial_checkBox = QCheckBox(self.Zipf_tab)
        self.Partial_checkBox.setObjectName(u"Partial_checkBox")
        self.Partial_checkBox.setGeometry(QRect(400, 310, 111, 20))
        icon6 = QIcon()
        icon6.addFile(u":/IR-System/resource/PartialSearch-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Partial_checkBox.setIcon(icon6)
        self.Partial_checkBox.setChecked(True)
        self.Match_lineEdit = QLineEdit(self.Zipf_tab)
        self.Match_lineEdit.setObjectName(u"Match_lineEdit")
        self.Match_lineEdit.setGeometry(QRect(80, 310, 161, 20))
        self.Match_tableWidget = QTableWidget(self.Zipf_tab)
        if (self.Match_tableWidget.columnCount() < 3):
            self.Match_tableWidget.setColumnCount(3)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.Match_tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.Match_tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.Match_tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem5)
        self.Match_tableWidget.setObjectName(u"Match_tableWidget")
        self.Match_tableWidget.setGeometry(QRect(10, 340, 741, 141))
        self.Match_tableWidget.setAutoFillBackground(False)
        self.Match_tableWidget.setFrameShadow(QFrame.Raised)
        self.tabWidget.addTab(self.Zipf_tab, "")
        self.Word2Vect_tab = QWidget()
        self.Word2Vect_tab.setObjectName(u"Word2Vect_tab")
        self.Traindata_lineEdit = QLineEdit(self.Word2Vect_tab)
        self.Traindata_lineEdit.setObjectName(u"Traindata_lineEdit")
        self.Traindata_lineEdit.setGeometry(QRect(130, 10, 191, 20))
        self.file_label_4 = QLabel(self.Word2Vect_tab)
        self.file_label_4.setObjectName(u"file_label_4")
        self.file_label_4.setGeometry(QRect(20, 10, 101, 16))
        self.Traindata_Button = QPushButton(self.Word2Vect_tab)
        self.Traindata_Button.setObjectName(u"Traindata_Button")
        self.Traindata_Button.setGeometry(QRect(330, 10, 21, 21))
        self.Word2Vect_tabWidget = QTabWidget(self.Word2Vect_tab)
        self.Word2Vect_tabWidget.setObjectName(u"Word2Vect_tabWidget")
        self.Word2Vect_tabWidget.setGeometry(QRect(10, 40, 741, 421))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.file_label_5 = QLabel(self.tab)
        self.file_label_5.setObjectName(u"file_label_5")
        self.file_label_5.setGeometry(QRect(10, 10, 101, 16))
        self.CBOW_tableWidget = QTableWidget(self.tab)
        if (self.CBOW_tableWidget.columnCount() < 2):
            self.CBOW_tableWidget.setColumnCount(2)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.CBOW_tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.CBOW_tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem7)
        self.CBOW_tableWidget.setObjectName(u"CBOW_tableWidget")
        self.CBOW_tableWidget.setGeometry(QRect(10, 40, 351, 341))
        self.CBOW_tableWidget.setFrameShadow(QFrame.Raised)
        self.CBOWCompute_Button = QPushButton(self.tab)
        self.CBOWCompute_Button.setObjectName(u"CBOWCompute_Button")
        self.CBOWCompute_Button.setGeometry(QRect(320, 10, 81, 20))
        icon7 = QIcon()
        icon7.addFile(u":/IR-System/resource/neurone.png", QSize(), QIcon.Normal, QIcon.Off)
        self.CBOWCompute_Button.setIcon(icon7)
        self.CBOWImage_label = QLabel(self.tab)
        self.CBOWImage_label.setObjectName(u"CBOWImage_label")
        self.CBOWImage_label.setGeometry(QRect(370, 40, 361, 341))
        self.TrainCBOWModel_comBox = QComboBox(self.tab)
        self.TrainCBOWModel_comBox.setObjectName(u"TrainCBOWModel_comBox")
        self.TrainCBOWModel_comBox.setGeometry(QRect(120, 10, 191, 22))
        self.TrainCBOWModel_comBox.setEditable(True)
        self.Word2Vect_tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.file_label_6 = QLabel(self.tab_2)
        self.file_label_6.setObjectName(u"file_label_6")
        self.file_label_6.setGeometry(QRect(10, 10, 101, 16))
        self.Skipgram_tableWidget = QTableWidget(self.tab_2)
        if (self.Skipgram_tableWidget.columnCount() < 2):
            self.Skipgram_tableWidget.setColumnCount(2)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.Skipgram_tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.Skipgram_tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem9)
        self.Skipgram_tableWidget.setObjectName(u"Skipgram_tableWidget")
        self.Skipgram_tableWidget.setGeometry(QRect(10, 40, 351, 341))
        self.Skipgram_tableWidget.setFrameShadow(QFrame.Raised)
        self.SkipgramCompute_Button = QPushButton(self.tab_2)
        self.SkipgramCompute_Button.setObjectName(u"SkipgramCompute_Button")
        self.SkipgramCompute_Button.setGeometry(QRect(320, 10, 81, 20))
        self.SkipgramCompute_Button.setIcon(icon7)
        self.SkipgramImage_label = QLabel(self.tab_2)
        self.SkipgramImage_label.setObjectName(u"SkipgramImage_label")
        self.SkipgramImage_label.setGeometry(QRect(370, 40, 361, 341))
        self.TrainSkipgramModel_comboBox = QComboBox(self.tab_2)
        self.TrainSkipgramModel_comboBox.setObjectName(u"TrainSkipgramModel_comboBox")
        self.TrainSkipgramModel_comboBox.setGeometry(QRect(120, 10, 191, 22))
        self.TrainSkipgramModel_comboBox.setEditable(True)
        self.Word2Vect_tabWidget.addTab(self.tab_2, "")
        self.CostTime_Label = QLabel(self.Word2Vect_tab)
        self.CostTime_Label.setObjectName(u"CostTime_Label")
        self.CostTime_Label.setGeometry(QRect(540, 10, 201, 20))
        self.file_label_7 = QLabel(self.Word2Vect_tab)
        self.file_label_7.setObjectName(u"file_label_7")
        self.file_label_7.setGeometry(QRect(370, 10, 41, 16))
        self.SimilarWord_comboBox = QComboBox(self.Word2Vect_tab)
        self.SimilarWord_comboBox.addItem("")
        self.SimilarWord_comboBox.addItem("")
        self.SimilarWord_comboBox.addItem("")
        self.SimilarWord_comboBox.addItem("")
        self.SimilarWord_comboBox.addItem("")
        self.SimilarWord_comboBox.setObjectName(u"SimilarWord_comboBox")
        self.SimilarWord_comboBox.setGeometry(QRect(420, 10, 101, 22))
        self.SimilarWord_comboBox.setEditable(True)
        self.SimilarWord_comboBox.setDuplicatesEnabled(False)
        self.tabWidget.addTab(self.Word2Vect_tab, "")
        QWidget.setTabOrder(self.func_comboBox, self.file_spinBox)
        QWidget.setTabOrder(self.file_spinBox, self.Stemming_checkBox)
        QWidget.setTabOrder(self.Stemming_checkBox, self.Stopwords_checkBox)
        QWidget.setTabOrder(self.Stopwords_checkBox, self.Index_tableWidget)

        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(1)
        self.Word2Vect_tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"IR-System", None))
        self.func_comboBox.setItemText(0, QCoreApplication.translate("Form", u"Information Retrieval", None))
        self.func_comboBox.setItemText(1, QCoreApplication.translate("Form", u"Contents Compare", None))
        self.func_comboBox.setItemText(2, QCoreApplication.translate("Form", u"Zipf Distribution", None))
        self.func_comboBox.setItemText(3, QCoreApplication.translate("Form", u"Matching", None))
        self.func_comboBox.setItemText(4, QCoreApplication.translate("Form", u"Edit Distance", None))
        self.func_comboBox.setItemText(5, QCoreApplication.translate("Form", u"Word2Vect", None))

        self.func_comboBox.setCurrentText(QCoreApplication.translate("Form", u"Information Retrieval", None))
        self.label.setText(QCoreApplication.translate("Form", u"Pelease select perform function", None))
        self.file_label.setText(QCoreApplication.translate("Form", u"Information Retrieval", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Amount of Files", None))
        self.Stemming_checkBox.setText(QCoreApplication.translate("Form", u"Porter Stemming", None))
        self.Stopwords_checkBox.setText(QCoreApplication.translate("Form", u"Stopwords", None))
        self.file_label_2.setText("")
        self.perform_pushButton.setText(QCoreApplication.translate("Form", u"Perform", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Index", None))
        ___qtablewidgetitem = self.Index_tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Form", u"Word", None));
        ___qtablewidgetitem1 = self.Index_tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Form", u"Document", None));
        ___qtablewidgetitem2 = self.Index_tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Form", u"Rows", None));
        self.IgnoreCase_checkBox.setText(QCoreApplication.translate("Form", u"Ignore case", None))
        self.file_label_3.setText(QCoreApplication.translate("Form", u"Matching :", None))
        self.search_pushButton.setText(QCoreApplication.translate("Form", u"Search", None))
        self.Partial_checkBox.setText(QCoreApplication.translate("Form", u"Partial matching", None))
        self.Match_lineEdit.setText(QCoreApplication.translate("Form", u"COVID-19", None))
        ___qtablewidgetitem3 = self.Match_tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Form", u"Word", None));
        ___qtablewidgetitem4 = self.Match_tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Form", u"Document", None));
        ___qtablewidgetitem5 = self.Match_tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Form", u"Rows", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Zipf_tab), QCoreApplication.translate("Form", u"Zipf Distribution", None))
        self.Traindata_lineEdit.setText(QCoreApplication.translate("Form", u"D:\\Training_CNBC_Data.txt", None))
        self.file_label_4.setText(QCoreApplication.translate("Form", u"Training Pattern", None))
        self.Traindata_Button.setText(QCoreApplication.translate("Form", u"...", None))
        self.file_label_5.setText(QCoreApplication.translate("Form", u"Training model", None))
        ___qtablewidgetitem6 = self.CBOW_tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Form", u"Similarity word", None));
        ___qtablewidgetitem7 = self.CBOW_tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Form", u"Score", None));
        self.CBOWCompute_Button.setText(QCoreApplication.translate("Form", u"Compute", None))
        self.CBOWImage_label.setText("")
        self.Word2Vect_tabWidget.setTabText(self.Word2Vect_tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"CBOW", None))
        self.file_label_6.setText(QCoreApplication.translate("Form", u"Training model", None))
        ___qtablewidgetitem8 = self.Skipgram_tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("Form", u"Similarity word", None));
        ___qtablewidgetitem9 = self.Skipgram_tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("Form", u"Score", None));
        self.SkipgramCompute_Button.setText(QCoreApplication.translate("Form", u"Compute", None))
        self.SkipgramImage_label.setText("")
        self.Word2Vect_tabWidget.setTabText(self.Word2Vect_tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"Skip-gram", None))
        self.CostTime_Label.setText("")
        self.file_label_7.setText(QCoreApplication.translate("Form", u"Word : ", None))
        self.SimilarWord_comboBox.setItemText(0, QCoreApplication.translate("Form", u"biden", None))
        self.SimilarWord_comboBox.setItemText(1, QCoreApplication.translate("Form", u"joe", None))
        self.SimilarWord_comboBox.setItemText(2, QCoreApplication.translate("Form", u"pfizer", None))
        self.SimilarWord_comboBox.setItemText(3, QCoreApplication.translate("Form", u"covid", None))
        self.SimilarWord_comboBox.setItemText(4, QCoreApplication.translate("Form", u"covid-19", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Word2Vect_tab), QCoreApplication.translate("Form", u"Word2Vec", None))
    # retranslateUi

